package proyecto2.pkg2;

import javax.swing.JOptionPane;
import javax.swing.*;

/**
 * Con la clase se obtiene la expresión a evaluar por el usuario. Y a su vez se
 * llaman a todas las funciones necesarias para construirlo correctamente
 *
 * @author Bryan Cariaco & Juan Ceballos
 */
public class Interfaz extends javax.swing.JFrame {

    ArbolBinarioExpresion arbol = new ArbolBinarioExpresion();

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        registrarInput = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        infija = new javax.swing.JButton();
        polaca = new javax.swing.JButton();
        polacaInversa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        espacioMostrar = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Árbol de Expresiones");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        inputArea.setColumns(20);
        inputArea.setRows(5);
        inputArea.setText("Ingrese la expresion a evaluar\n");
        jScrollPane1.setViewportView(inputArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 150));

        registrarInput.setText("Registrar Expresión");
        registrarInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarInputActionPerformed(evt);
            }
        });
        jPanel1.add(registrarInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modos para mostrar la expresión:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        infija.setText("Infija");
        infija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infijaActionPerformed(evt);
            }
        });
        jPanel1.add(infija, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, -1));

        polaca.setText("Polaca");
        polaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polacaActionPerformed(evt);
            }
        });
        jPanel1.add(polaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 100, -1));

        polacaInversa.setText("Polaca Inversa");
        polacaInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polacaInversaActionPerformed(evt);
            }
        });
        jPanel1.add(polacaInversa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        espacioMostrar.setColumns(20);
        espacioMostrar.setRows(5);
        espacioMostrar.setText("Espacio para mostrar\n");
        jScrollPane2.setViewportView(espacioMostrar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 390, 380, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void polacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polacaActionPerformed
        // TODO add your handling code here:
        try {
            espacioMostrar.setText("");
            arbol.setMostrable("");
            if (arbol.getRaiz() != null) {
                arbol.Preorden(arbol.getRaiz());
                String texto = arbol.getMostrable();
                espacioMostrar.setText(texto);
            } else {
                JOptionPane.showMessageDialog(null, "El árbol está vacio");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_polacaActionPerformed

    private void registrarInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarInputActionPerformed
        // TODO add your handling code here:
        try {
            String contenido = inputArea.getText();
            arbol.crearArchivo(contenido);
            arbol.leerDatos();
            arbol.tipoEntrada(arbol.getEvaluado());
            arbol.crearArbol(arbol.getTipoEntrada());
            if (arbol.verificarExpresion(contenido)) {

                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        JFrame frame = new ArbolBinarioGrafico(arbol);
                        frame.setSize(400, 400);
                        frame.setLocationRelativeTo(null);
                        frame.setVisible(true);
                    }
                });
                inputArea.setText("");
            } else {
                arbol.setRaiz(null);
                JOptionPane.showMessageDialog(null, "Expresión ingresada errónea");
            }
            arbol.setMostrable("");
            arbol.setEvaluado("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_registrarInputActionPerformed

    private void infijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infijaActionPerformed
        // TODO add your handling code here:
        try {
            espacioMostrar.setText("");
            arbol.setMostrable("");
            if (arbol.getRaiz() != null) {
                arbol.Inorden(arbol.getRaiz());
                String texto = arbol.getMostrable();
                espacioMostrar.setText(texto);
            } else {
                JOptionPane.showMessageDialog(null, "El árbol está vacio");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_infijaActionPerformed

    private void polacaInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polacaInversaActionPerformed
        // TODO add your handling code here:
        try {
            espacioMostrar.setText("");
            arbol.setMostrable("");
            if (arbol.getRaiz() != null) {
                arbol.Postorden(arbol.getRaiz());
                String texto = arbol.getMostrable();
                espacioMostrar.setText(texto);
            } else {
                JOptionPane.showMessageDialog(null, "El árbol está vacio");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_polacaInversaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea espacioMostrar;
    private javax.swing.JButton infija;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton polaca;
    private javax.swing.JButton polacaInversa;
    private javax.swing.JButton registrarInput;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
